version: '2.4'

services:

  health-proxy:
    image: debian:stretch
    command: sleep infinity
    depends_on:
      transaction-processor:
        condition: service_healthy

  transaction-processor:
    build: transaction-processor
    environment:
      JAVAOPTS_DEBUG: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006"
    ports:
      - "8080"

  integration-tests:
    build: integration-tests

    depends_on:
      health-proxy:
        condition: service_started
